name 'db_server_installation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures db_server_installation'
long_description 'Installs/Configures db_server_installation'
version '0.1.0'
